version: '4.31'

services:
  app:
    container_name: quirky_brown
    image: docker.io/cloud/loginserver
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - cloud
    networks:
      - cloud_network

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app
    environment:
      - NODE_ENV=development
      - PGHOST=cloud
      - PGUSER=postgres
      - PGPASSWORD=1234
      - PGDATABASE=CLOUD
    depends_on:
      - cloud
    networks:

  cloud:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: CLOUD
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - cloud_network

networks:
  my_macvlan_network:
    external: true